name: Build on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        use-vulkan: [ true, false ]
        os: [ ubuntu-18.04, ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}
    name: "Build on ${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v2

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install libnetcdf-dev libglm-dev libopenmpi-dev \
        ocl-icd-opencl-dev opencl-headers clinfo nvidia-cuda-dev nvidia-cuda-toolkit

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
